Repository nbcam12/Nb_Contact, pull requests merged in 2023-09, with the labels that each got.

#2 test
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
Labels: feature

#8 test
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
Labels: feature

#15 [DESIGN] : 🎨 MainActivity 디자인 배치 완료
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_dialpad_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
Labels: UI

#17 Feature/main
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/main/TabModel.kt
  app/src/main/java/com/example/contact_nb12/main/ViewPagerAdapter.kt
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#26 [DESIGN] : 🎨 디테일페이지 UI 기초제작
  app/src/main/res/drawable/backarrow.xml
  app/src/main/res/drawable/delete.xml
  app/src/main/res/drawable/message.xml
  app/src/main/res/drawable/phone.xml
  app/src/main/res/drawable/sample_4.jpg
  app/src/main/res/drawable/userswitch.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: UI

#21 Feature/main fab
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
Labels: feature

#30 [DESIGN] : 🎨 디테일페이지 UI 이미지 테두리 둥굴게 구현
  app/src/main/res/drawable/round.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: UI

#31 [FEAT] : ⚙ editButton 디자인 및 외부사용용 메서드 생성
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/res/drawable/icon_edit.png
  app/src/main/res/layout/main_activity.xml
Labels: feature, UI

#33 [FEAT] : ⚙️ 마이페이지 수정 visible 적용
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: feature

#35 Feature/contactlist
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/list/DataManager.kt
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/main/TabModel.kt
  app/src/main/java/com/example/contact_nb12/main/ViewPagerAdapter.kt
  app/src/main/java/com/example/contact_nb12/models/Contact.kt
  app/src/main/res/drawable/backarrow.xml
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_dialpad_24.xml
  app/src/main/res/drawable/call.png
  app/src/main/res/drawable/default_profile.png
  app/src/main/res/drawable/delete.xml
  app/src/main/res/drawable/full_star.png
  app/src/main/res/drawable/icon_edit.png
  app/src/main/res/drawable/message.xml
  app/src/main/res/drawable/mypage_img_back.xml
  app/src/main/res/drawable/phone.xml
  app/src/main/res/drawable/placeholder.png
  app/src/main/res/drawable/round.xml
  app/src/main/res/drawable/rounded.xml
  app/src/main/res/drawable/sample1.jpg
  app/src/main/res/drawable/sample_4.jpg
  app/src/main/res/drawable/star.png
  app/src/main/res/drawable/userswitch.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_viewtype_bookmark.xml
  app/src/main/res/layout/item_viewtype_normal.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#36 [FEAT] : ⚙️ DetailPage Activity 추가 및 전화걸기 데이터 값 받아오기 기초 틀 구현
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/java/com/example/contact_nb12/detail/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#37 [FEAT] : ⚙️ DetailFragement 누락으로 인한 재 PR
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
Labels: feature

#39 [FEAT] : ⚙️ 연락처 리스트 intent 처리
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/models/Contact.kt
Labels: feature

#41 [FEAT] : ⚙️ 마이페이지 UI 수정 및 편집 기능
  .idea/render.experimental.xml
  app/build.gradle
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/drawable/dialog_border.xml
  app/src/main/res/drawable/dialog_profile.png
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature, UI

#45 [FEAT] : ⚙️ edit수정 가능
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#47 [FEAT] : ⚙️ DetailFragement 데이터 가져오기 및 뒤로가기 기능 구현
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/java/com/example/contact_nb12/detail/DetailActivity.kt
Labels: feature

#50 [FEAT] : ⚙️ DetailFragement 스크롤기능 구현
  .idea/misc.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: feature

#52 [FEAT] : ⚙️ 내 정보 사진 변경 & 다이얼로그
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/drawable/mypage_img_back.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#53 [FEAT] : ⚙ 연락처 리스트 스와이프 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/list/ItemTouchHelperCallback.kt
  app/src/main/java/com/example/contact_nb12/main/ViewPagerAdapter.kt
Labels: feature

#54 Feature/load contact
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/main/ViewPagerAdapter.kt
Labels: feature

#61 [FEAT] : ⚙️ 다이얼로그에서 사진 편집 기능
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
Labels: feature

#63 Feature/load contact
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/main/ViewPagerAdapter.kt
  app/src/main/res/values/strings.xml
Labels: feature

#65 [FEAT] : ⚙️ DetailFragement 편집기능 구현
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/java/com/example/contact_nb12/detail/DetailActivity.kt
  app/src/main/java/com/example/contact_nb12/main/MainActivity.kt
  app/src/main/java/com/example/contact_nb12/mypage/AddContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/drawable/baseline_edit_24.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: feature

#71 Feature/updatelist
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/res/layout/item_viewtype_bookmark.xml
  app/src/main/res/layout/item_viewtype_normal.xml
Labels: feature, UI

#72 Feature/listmy
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/contact_nb12/detail/DetailActivity.kt
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/java/com/example/contact_nb12/list/ContactAddDialog.kt
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/list/DataManager.kt
  app/src/main/java/com/example/contact_nb12/models/Contact.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#73 [DESIGN] : 🎨 ⚙️ Detail 페이지 휴지통, 메세지 아이콘 삭제 및 스크롤 범위 변경
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: UI

#77 [FIX] : 🔧 Image BugFix
  app/build.gradle
  app/src/main/java/com/example/contact_nb12/Util/Utils.kt
  app/src/main/java/com/example/contact_nb12/detail/ContactDetailFragment.kt
  app/src/main/java/com/example/contact_nb12/detail/DetailActivity.kt
  app/src/main/java/com/example/contact_nb12/list/ContactAdapter.kt
  app/src/main/java/com/example/contact_nb12/list/ContactAddDialog.kt
  app/src/main/java/com/example/contact_nb12/list/ContactListFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/EditContactDialogFragment.kt
  app/src/main/java/com/example/contact_nb12/mypage/MyPageFragment.kt
Labels: feature, bug
